import type { KanbanTab, LeadCard, SmartColumn } from "./types";

export const TABS: KanbanTab[] = [
  "Leads",
  "Clientes",
  "Pós-venda",
  "Indicações",
  "Recuperação",
  "Campanhas",
  "Influenciadores",
];

export const COLUMNS_BY_TAB: Record<KanbanTab, SmartColumn[]> = {
  Leads: ["Leads do dia", "Novo contato", "Em atendimento", "Interessado", "Orçamento enviado", "Não fechou"],
  Clientes: ["Em atendimento", "Interessado", "Fidelização", "Cliente em risco"],
  "Pós-venda": ["Pós-venda", "Fidelização", "Cliente em risco"],
  Indicações: ["Indicações", "Novo contato", "Em atendimento"],
  Recuperação: ["Cliente em risco", "Cliente inativo", "Recuperados"],
  Campanhas: ["Leads do dia", "Em atendimento", "Interessado", "Não fechou"],
  Influenciadores: ["Leads do dia", "Novo contato", "Em atendimento", "Interessado"],
};

export const COLUMN_META: Record<SmartColumn, { hint: string; tone: string }> = {
  "Leads do dia":        { hint: "Chegaram hoje",                tone: "bg-chart-4/15 text-foreground" },
  "Novo contato":        { hint: "Sem atendimento ainda",        tone: "bg-secondary text-muted-foreground" },
  "Em atendimento":      { hint: "Conversando agora",            tone: "bg-primary/15 text-primary" },
  "Interessado":         { hint: "Demonstrou intenção",          tone: "bg-accent/15 text-accent" },
  "Orçamento enviado":   { hint: "Proposta enviada",             tone: "bg-chart-2/20 text-foreground" },
  "Não fechou":          { hint: "Recusou ou parou",             tone: "bg-muted text-muted-foreground" },
  "Cliente em risco":    { hint: "Queda de interação",           tone: "bg-destructive/10 text-destructive" },
  "Cliente inativo":     { hint: "Há muito sem comprar",         tone: "bg-destructive/10 text-destructive" },
  "Pós-venda":           { hint: "Acompanhamento",               tone: "bg-chart-2/15 text-foreground" },
  "Fidelização":         { hint: "Recorrentes",                  tone: "bg-success/15 text-success" },
  "Indicações":          { hint: "Indicando amigos",             tone: "bg-accent/15 text-accent" },
  "Recuperados":         { hint: "Voltaram com campanha",        tone: "bg-success/15 text-success" },
};

export const LEADS_MOCK: LeadCard[] = [
  {
    id: "L001", nome: "Marina Costa", telefone: "(11) 99812-3344",
    tags: ["VIP", "Cachorro"], origem: "Influenciador", origemDetalhe: "Story · @gabipets",
    utmSource: "instagram", utmCampaign: "gabi-pet-mar", influenciador: "@gabipets", cupom: "GABI10",
    custoLead: 4.2, primeiroContato: "16/04", tempoAteCompra: 2, ultimaInteracao: "12min", diasSemInteracao: 0,
    comprasRealizadas: 14, ticketMedio: 210, produtosFavoritos: ["Golden 15kg", "Petisco natural"],
    pontos: 480, indicacoesFeitas: 3, campanhasRecebidas: ["Black Pet", "Recompra IA"],
    ultimoAtendimento: "Hoje 14:32", statusRelacionamento: "Forte",
    intent: "comprando", priority: "urgente", churnRisk: 8,
    column: "Em atendimento", tab: "Leads", valorPotencial: 320,
  },
  {
    id: "L002", nome: "Pedro Alves", telefone: "(11) 99423-7788",
    tags: ["Econômico"], origem: "Meta Ads", origemDetalhe: "Black Pet · Nov",
    utmSource: "facebook", utmCampaign: "black-pet-nov", anuncio: "Carrossel Premier",
    custoLead: 22, primeiroContato: "02/05", tempoAteCompra: 1, ultimaInteracao: "18min", diasSemInteracao: 0,
    comprasRealizadas: 8, ticketMedio: 95, produtosFavoritos: ["Premier Filhotes 3kg"],
    pontos: 90, indicacoesFeitas: 0, campanhasRecebidas: ["Black Pet"],
    ultimoAtendimento: "Hoje 14:18", statusRelacionamento: "Estável",
    intent: "morno", priority: "media", churnRisk: 22,
    column: "Leads do dia", tab: "Leads", valorPotencial: 95,
  },
  {
    id: "L003", nome: "Júlia Ramos", telefone: "(11) 98011-2231",
    tags: ["Premium", "2 pets"], origem: "Instagram", origemDetalhe: "Reels viral",
    utmSource: "instagram-organic",
    custoLead: 0, primeiroContato: "10/04", tempoAteCompra: 3, ultimaInteracao: "1h", diasSemInteracao: 0,
    comprasRealizadas: 16, ticketMedio: 280, produtosFavoritos: ["Shampoo hipo", "Royal Canin Felino"],
    pontos: 720, indicacoesFeitas: 2, campanhasRecebidas: ["Combo gato+cão"],
    ultimoAtendimento: "Hoje 13:50", statusRelacionamento: "Forte",
    intent: "quente", priority: "alta", churnRisk: 12,
    column: "Interessado", tab: "Leads", valorPotencial: 280,
  },
  {
    id: "L004", nome: "Carlos Mendes", telefone: "(11) 97812-5599",
    tags: ["VIP", "Indicado"], origem: "Indicação", origemDetalhe: "Indicado por João Silva",
    custoLead: 0, primeiroContato: "27/04", tempoAteCompra: 1, ultimaInteracao: "4h", diasSemInteracao: 0,
    comprasRealizadas: 14, ticketMedio: 142, produtosFavoritos: ["Hills Felino"],
    pontos: 360, indicacoesFeitas: 4, campanhasRecebidas: ["Indicação 10%"],
    ultimoAtendimento: "Hoje 13:14", statusRelacionamento: "Forte",
    intent: "morno", priority: "media", churnRisk: 14,
    column: "Pós-venda", tab: "Pós-venda", valorPotencial: 142,
  },
  {
    id: "L005", nome: "Ana Beatriz", telefone: "(11) 99988-1144",
    tags: ["Premium", "Cachorro"], origem: "TikTok", origemDetalhe: "Reels orgânico #petlovers",
    utmSource: "tiktok-organic",
    custoLead: 0, primeiroContato: "20/04", tempoAteCompra: 2, ultimaInteracao: "3h", diasSemInteracao: 0,
    comprasRealizadas: 16, ticketMedio: 320, produtosFavoritos: ["Premier Gourmet"],
    pontos: 540, indicacoesFeitas: 1, campanhasRecebidas: ["Recompra IA"],
    ultimoAtendimento: "Hoje 12:58", statusRelacionamento: "Forte",
    intent: "quente", priority: "alta", churnRisk: 10,
    column: "Fidelização", tab: "Clientes", valorPotencial: 320,
  },
  {
    id: "L006", nome: "Roberto Lima", telefone: "(11) 98234-6677",
    tags: ["VIP", "Raça grande"], origem: "Google", origemDetalhe: "Search · ração premium",
    utmSource: "google-ads", utmCampaign: "search-racao-premium", anuncio: "Ad Golden 20kg",
    custoLead: 38, primeiroContato: "23/04", tempoAteCompra: 1, ultimaInteracao: "30min", diasSemInteracao: 0,
    comprasRealizadas: 14, ticketMedio: 540, produtosFavoritos: ["Golden 20kg"],
    pontos: 820, indicacoesFeitas: 0, campanhasRecebidas: ["Search ração premium"],
    ultimoAtendimento: "Hoje 12:30", statusRelacionamento: "Forte",
    intent: "comprando", priority: "urgente", churnRisk: 9,
    column: "Orçamento enviado", tab: "Leads", valorPotencial: 540,
  },
  {
    id: "L007", nome: "Helena Souza", telefone: "(11) 97001-2233",
    tags: ["Risco"], origem: "WhatsApp", origemDetalhe: "Contato direto",
    custoLead: 0, primeiroContato: "13/03", ultimaInteracao: "62d", diasSemInteracao: 62,
    comprasRealizadas: 3, ticketMedio: 78, produtosFavoritos: ["Whiskas 3kg"],
    pontos: 30, indicacoesFeitas: 0, campanhasRecebidas: ["Reativação"],
    ultimoAtendimento: "13/03", statusRelacionamento: "Frágil",
    intent: "frio", priority: "alta", churnRisk: 84,
    column: "Cliente em risco", tab: "Recuperação", valorPotencial: 78,
  },
  {
    id: "L008", nome: "Lucas Pereira", telefone: "(11) 98765-4321",
    tags: ["Novo"], origem: "QR Code", origemDetalhe: "Embalagem ração",
    custoLead: 1.8, primeiroContato: "Hoje", ultimaInteracao: "5min", diasSemInteracao: 0,
    comprasRealizadas: 0, ticketMedio: 0, produtosFavoritos: [],
    pontos: 0, indicacoesFeitas: 0, campanhasRecebidas: [],
    ultimoAtendimento: "—", statusRelacionamento: "Inicial",
    intent: "morno", priority: "media", churnRisk: 30,
    column: "Leads do dia", tab: "Leads", valorPotencial: 120,
  },
  {
    id: "L009", nome: "Beatriz Nunes", telefone: "(11) 99111-2222",
    tags: ["Indicadora"], origem: "Indicação", origemDetalhe: "Indicou 3 amigos este mês",
    custoLead: 0, primeiroContato: "12/02", ultimaInteracao: "2d", diasSemInteracao: 2,
    comprasRealizadas: 9, ticketMedio: 180, produtosFavoritos: ["Areia higiênica"],
    pontos: 410, indicacoesFeitas: 6, campanhasRecebidas: ["Indica e ganha"],
    ultimoAtendimento: "2 dias atrás", statusRelacionamento: "Forte",
    intent: "morno", priority: "alta", churnRisk: 18,
    column: "Indicações", tab: "Indicações", valorPotencial: 180,
  },
  {
    id: "L010", nome: "Diego Martins", telefone: "(11) 99000-1234",
    tags: ["Recuperado"], origem: "Cupom", origemDetalhe: "VOLTA15 · campanha SMS",
    cupom: "VOLTA15",
    custoLead: 6, primeiroContato: "Hoje", ultimaInteracao: "1h", diasSemInteracao: 0,
    comprasRealizadas: 5, ticketMedio: 130, produtosFavoritos: ["Coleira", "Brinquedo"],
    pontos: 140, indicacoesFeitas: 0, campanhasRecebidas: ["Reativação SMS", "VOLTA15"],
    ultimoAtendimento: "Hoje 11:00", statusRelacionamento: "Reaquecendo",
    intent: "quente", priority: "alta", churnRisk: 25,
    column: "Recuperados", tab: "Recuperação", valorPotencial: 130,
  },
  {
    id: "L011", nome: "Sofia Almeida", telefone: "(11) 98555-7788",
    tags: ["Inativa"], origem: "Meta Ads", origemDetalhe: "Lookalike VIP",
    utmSource: "facebook", utmCampaign: "lookalike-vip",
    custoLead: 12, primeiroContato: "10/01", ultimaInteracao: "98d", diasSemInteracao: 98,
    comprasRealizadas: 2, ticketMedio: 110, produtosFavoritos: [],
    pontos: 20, indicacoesFeitas: 0, campanhasRecebidas: [],
    ultimoAtendimento: "10/01", statusRelacionamento: "Inativo",
    intent: "frio", priority: "media", churnRisk: 92,
    column: "Cliente inativo", tab: "Recuperação", valorPotencial: 110,
  },
  {
    id: "L012", nome: "Rafael Torres", telefone: "(11) 98222-3344",
    tags: ["Influenciador"], origem: "Influenciador", origemDetalhe: "Parceria @petlovers",
    influenciador: "@petlovers",
    custoLead: 5.5, primeiroContato: "Hoje", ultimaInteracao: "20min", diasSemInteracao: 0,
    comprasRealizadas: 0, ticketMedio: 0, produtosFavoritos: [],
    pontos: 0, indicacoesFeitas: 0, campanhasRecebidas: ["Parceria @petlovers"],
    ultimoAtendimento: "—", statusRelacionamento: "Inicial",
    intent: "quente", priority: "alta", churnRisk: 20,
    column: "Novo contato", tab: "Influenciadores", valorPotencial: 240,
  },
];
