/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecompraPrevistaRouteImport } from './routes/recompra-prevista'
import { Route as ProdutosProcuradosRouteImport } from './routes/produtos-procurados'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as IndicacoesRouteImport } from './routes/indicacoes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EntregasRouteImport } from './routes/entregas'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebhookWhatsappRouteImport } from './routes/api/webhook.whatsapp'
import { Route as ApiWebhookPagamentoRouteImport } from './routes/api/webhook.pagamento'
import { Route as ApiUazapiTestRouteImport } from './routes/api/uazapi.test'
import { Route as ApiMercadopagoWebhookRouteImport } from './routes/api/mercadopago.webhook'
import { Route as ApiCrmProdutosProcuradosRouteImport } from './routes/api/crm.produtos-procurados'
import { Route as ApiCrmProdutosRouteImport } from './routes/api/crm.produtos'
import { Route as ApiCrmPixRouteImport } from './routes/api/crm.pix'
import { Route as ApiCrmPedidosRouteImport } from './routes/api/crm.pedidos'
import { Route as ApiCrmIndicacoesRouteImport } from './routes/api/crm.indicacoes'
import { Route as ApiCrmDashboardRouteImport } from './routes/api/crm.dashboard'
import { Route as ApiCrmConversasRouteImport } from './routes/api/crm.conversas'
import { Route as ApiCrmClientesRouteImport } from './routes/api/crm.clientes'
import { Route as ApiCrmAssistenteRouteImport } from './routes/api/crm.assistente'

const RecompraPrevistaRoute = RecompraPrevistaRouteImport.update({
  id: '/recompra-prevista',
  path: '/recompra-prevista',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosProcuradosRoute = ProdutosProcuradosRouteImport.update({
  id: '/produtos-procurados',
  path: '/produtos-procurados',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacoesRoute = IndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasRoute = EntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookWhatsappRoute = ApiWebhookWhatsappRouteImport.update({
  id: '/api/webhook/whatsapp',
  path: '/api/webhook/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookPagamentoRoute = ApiWebhookPagamentoRouteImport.update({
  id: '/api/webhook/pagamento',
  path: '/api/webhook/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUazapiTestRoute = ApiUazapiTestRouteImport.update({
  id: '/api/uazapi/test',
  path: '/api/uazapi/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMercadopagoWebhookRoute = ApiMercadopagoWebhookRouteImport.update({
  id: '/api/mercadopago/webhook',
  path: '/api/mercadopago/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmProdutosProcuradosRoute =
  ApiCrmProdutosProcuradosRouteImport.update({
    id: '/api/crm/produtos-procurados',
    path: '/api/crm/produtos-procurados',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCrmProdutosRoute = ApiCrmProdutosRouteImport.update({
  id: '/api/crm/produtos',
  path: '/api/crm/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmPixRoute = ApiCrmPixRouteImport.update({
  id: '/api/crm/pix',
  path: '/api/crm/pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmPedidosRoute = ApiCrmPedidosRouteImport.update({
  id: '/api/crm/pedidos',
  path: '/api/crm/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmIndicacoesRoute = ApiCrmIndicacoesRouteImport.update({
  id: '/api/crm/indicacoes',
  path: '/api/crm/indicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmDashboardRoute = ApiCrmDashboardRouteImport.update({
  id: '/api/crm/dashboard',
  path: '/api/crm/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmConversasRoute = ApiCrmConversasRouteImport.update({
  id: '/api/crm/conversas',
  path: '/api/crm/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmClientesRoute = ApiCrmClientesRouteImport.update({
  id: '/api/crm/clientes',
  path: '/api/crm/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmAssistenteRoute = ApiCrmAssistenteRouteImport.update({
  id: '/api/crm/assistente',
  path: '/api/crm/assistente',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/campanhas': typeof CampanhasRoute
  '/clientes': typeof ClientesRoute
  '/conversas': typeof ConversasRoute
  '/entregas': typeof EntregasRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/indicacoes': typeof IndicacoesRoute
  '/pdv': typeof PdvRoute
  '/pedidos': typeof PedidosRoute
  '/produtos-procurados': typeof ProdutosProcuradosRoute
  '/recompra-prevista': typeof RecompraPrevistaRoute
  '/api/crm/assistente': typeof ApiCrmAssistenteRoute
  '/api/crm/clientes': typeof ApiCrmClientesRoute
  '/api/crm/conversas': typeof ApiCrmConversasRoute
  '/api/crm/dashboard': typeof ApiCrmDashboardRoute
  '/api/crm/indicacoes': typeof ApiCrmIndicacoesRoute
  '/api/crm/pedidos': typeof ApiCrmPedidosRoute
  '/api/crm/pix': typeof ApiCrmPixRoute
  '/api/crm/produtos': typeof ApiCrmProdutosRoute
  '/api/crm/produtos-procurados': typeof ApiCrmProdutosProcuradosRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/api/uazapi/test': typeof ApiUazapiTestRoute
  '/api/webhook/pagamento': typeof ApiWebhookPagamentoRoute
  '/api/webhook/whatsapp': typeof ApiWebhookWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/campanhas': typeof CampanhasRoute
  '/clientes': typeof ClientesRoute
  '/conversas': typeof ConversasRoute
  '/entregas': typeof EntregasRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/indicacoes': typeof IndicacoesRoute
  '/pdv': typeof PdvRoute
  '/pedidos': typeof PedidosRoute
  '/produtos-procurados': typeof ProdutosProcuradosRoute
  '/recompra-prevista': typeof RecompraPrevistaRoute
  '/api/crm/assistente': typeof ApiCrmAssistenteRoute
  '/api/crm/clientes': typeof ApiCrmClientesRoute
  '/api/crm/conversas': typeof ApiCrmConversasRoute
  '/api/crm/dashboard': typeof ApiCrmDashboardRoute
  '/api/crm/indicacoes': typeof ApiCrmIndicacoesRoute
  '/api/crm/pedidos': typeof ApiCrmPedidosRoute
  '/api/crm/pix': typeof ApiCrmPixRoute
  '/api/crm/produtos': typeof ApiCrmProdutosRoute
  '/api/crm/produtos-procurados': typeof ApiCrmProdutosProcuradosRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/api/uazapi/test': typeof ApiUazapiTestRoute
  '/api/webhook/pagamento': typeof ApiWebhookPagamentoRoute
  '/api/webhook/whatsapp': typeof ApiWebhookWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/campanhas': typeof CampanhasRoute
  '/clientes': typeof ClientesRoute
  '/conversas': typeof ConversasRoute
  '/entregas': typeof EntregasRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/indicacoes': typeof IndicacoesRoute
  '/pdv': typeof PdvRoute
  '/pedidos': typeof PedidosRoute
  '/produtos-procurados': typeof ProdutosProcuradosRoute
  '/recompra-prevista': typeof RecompraPrevistaRoute
  '/api/crm/assistente': typeof ApiCrmAssistenteRoute
  '/api/crm/clientes': typeof ApiCrmClientesRoute
  '/api/crm/conversas': typeof ApiCrmConversasRoute
  '/api/crm/dashboard': typeof ApiCrmDashboardRoute
  '/api/crm/indicacoes': typeof ApiCrmIndicacoesRoute
  '/api/crm/pedidos': typeof ApiCrmPedidosRoute
  '/api/crm/pix': typeof ApiCrmPixRoute
  '/api/crm/produtos': typeof ApiCrmProdutosRoute
  '/api/crm/produtos-procurados': typeof ApiCrmProdutosProcuradosRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/api/uazapi/test': typeof ApiUazapiTestRoute
  '/api/webhook/pagamento': typeof ApiWebhookPagamentoRoute
  '/api/webhook/whatsapp': typeof ApiWebhookWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/campanhas'
    | '/clientes'
    | '/conversas'
    | '/entregas'
    | '/estoque'
    | '/financeiro'
    | '/indicacoes'
    | '/pdv'
    | '/pedidos'
    | '/produtos-procurados'
    | '/recompra-prevista'
    | '/api/crm/assistente'
    | '/api/crm/clientes'
    | '/api/crm/conversas'
    | '/api/crm/dashboard'
    | '/api/crm/indicacoes'
    | '/api/crm/pedidos'
    | '/api/crm/pix'
    | '/api/crm/produtos'
    | '/api/crm/produtos-procurados'
    | '/api/mercadopago/webhook'
    | '/api/uazapi/test'
    | '/api/webhook/pagamento'
    | '/api/webhook/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/campanhas'
    | '/clientes'
    | '/conversas'
    | '/entregas'
    | '/estoque'
    | '/financeiro'
    | '/indicacoes'
    | '/pdv'
    | '/pedidos'
    | '/produtos-procurados'
    | '/recompra-prevista'
    | '/api/crm/assistente'
    | '/api/crm/clientes'
    | '/api/crm/conversas'
    | '/api/crm/dashboard'
    | '/api/crm/indicacoes'
    | '/api/crm/pedidos'
    | '/api/crm/pix'
    | '/api/crm/produtos'
    | '/api/crm/produtos-procurados'
    | '/api/mercadopago/webhook'
    | '/api/uazapi/test'
    | '/api/webhook/pagamento'
    | '/api/webhook/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/campanhas'
    | '/clientes'
    | '/conversas'
    | '/entregas'
    | '/estoque'
    | '/financeiro'
    | '/indicacoes'
    | '/pdv'
    | '/pedidos'
    | '/produtos-procurados'
    | '/recompra-prevista'
    | '/api/crm/assistente'
    | '/api/crm/clientes'
    | '/api/crm/conversas'
    | '/api/crm/dashboard'
    | '/api/crm/indicacoes'
    | '/api/crm/pedidos'
    | '/api/crm/pix'
    | '/api/crm/produtos'
    | '/api/crm/produtos-procurados'
    | '/api/mercadopago/webhook'
    | '/api/uazapi/test'
    | '/api/webhook/pagamento'
    | '/api/webhook/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  CampanhasRoute: typeof CampanhasRoute
  ClientesRoute: typeof ClientesRoute
  ConversasRoute: typeof ConversasRoute
  EntregasRoute: typeof EntregasRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  IndicacoesRoute: typeof IndicacoesRoute
  PdvRoute: typeof PdvRoute
  PedidosRoute: typeof PedidosRoute
  ProdutosProcuradosRoute: typeof ProdutosProcuradosRoute
  RecompraPrevistaRoute: typeof RecompraPrevistaRoute
  ApiCrmAssistenteRoute: typeof ApiCrmAssistenteRoute
  ApiCrmClientesRoute: typeof ApiCrmClientesRoute
  ApiCrmConversasRoute: typeof ApiCrmConversasRoute
  ApiCrmDashboardRoute: typeof ApiCrmDashboardRoute
  ApiCrmIndicacoesRoute: typeof ApiCrmIndicacoesRoute
  ApiCrmPedidosRoute: typeof ApiCrmPedidosRoute
  ApiCrmPixRoute: typeof ApiCrmPixRoute
  ApiCrmProdutosRoute: typeof ApiCrmProdutosRoute
  ApiCrmProdutosProcuradosRoute: typeof ApiCrmProdutosProcuradosRoute
  ApiMercadopagoWebhookRoute: typeof ApiMercadopagoWebhookRoute
  ApiUazapiTestRoute: typeof ApiUazapiTestRoute
  ApiWebhookPagamentoRoute: typeof ApiWebhookPagamentoRoute
  ApiWebhookWhatsappRoute: typeof ApiWebhookWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recompra-prevista': {
      id: '/recompra-prevista'
      path: '/recompra-prevista'
      fullPath: '/recompra-prevista'
      preLoaderRoute: typeof RecompraPrevistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos-procurados': {
      id: '/produtos-procurados'
      path: '/produtos-procurados'
      fullPath: '/produtos-procurados'
      preLoaderRoute: typeof ProdutosProcuradosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacoes': {
      id: '/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof IndicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas': {
      id: '/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof EntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/whatsapp': {
      id: '/api/webhook/whatsapp'
      path: '/api/webhook/whatsapp'
      fullPath: '/api/webhook/whatsapp'
      preLoaderRoute: typeof ApiWebhookWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/pagamento': {
      id: '/api/webhook/pagamento'
      path: '/api/webhook/pagamento'
      fullPath: '/api/webhook/pagamento'
      preLoaderRoute: typeof ApiWebhookPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uazapi/test': {
      id: '/api/uazapi/test'
      path: '/api/uazapi/test'
      fullPath: '/api/uazapi/test'
      preLoaderRoute: typeof ApiUazapiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mercadopago/webhook': {
      id: '/api/mercadopago/webhook'
      path: '/api/mercadopago/webhook'
      fullPath: '/api/mercadopago/webhook'
      preLoaderRoute: typeof ApiMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/produtos-procurados': {
      id: '/api/crm/produtos-procurados'
      path: '/api/crm/produtos-procurados'
      fullPath: '/api/crm/produtos-procurados'
      preLoaderRoute: typeof ApiCrmProdutosProcuradosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/produtos': {
      id: '/api/crm/produtos'
      path: '/api/crm/produtos'
      fullPath: '/api/crm/produtos'
      preLoaderRoute: typeof ApiCrmProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/pix': {
      id: '/api/crm/pix'
      path: '/api/crm/pix'
      fullPath: '/api/crm/pix'
      preLoaderRoute: typeof ApiCrmPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/pedidos': {
      id: '/api/crm/pedidos'
      path: '/api/crm/pedidos'
      fullPath: '/api/crm/pedidos'
      preLoaderRoute: typeof ApiCrmPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/indicacoes': {
      id: '/api/crm/indicacoes'
      path: '/api/crm/indicacoes'
      fullPath: '/api/crm/indicacoes'
      preLoaderRoute: typeof ApiCrmIndicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/dashboard': {
      id: '/api/crm/dashboard'
      path: '/api/crm/dashboard'
      fullPath: '/api/crm/dashboard'
      preLoaderRoute: typeof ApiCrmDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/conversas': {
      id: '/api/crm/conversas'
      path: '/api/crm/conversas'
      fullPath: '/api/crm/conversas'
      preLoaderRoute: typeof ApiCrmConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/clientes': {
      id: '/api/crm/clientes'
      path: '/api/crm/clientes'
      fullPath: '/api/crm/clientes'
      preLoaderRoute: typeof ApiCrmClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/assistente': {
      id: '/api/crm/assistente'
      path: '/api/crm/assistente'
      fullPath: '/api/crm/assistente'
      preLoaderRoute: typeof ApiCrmAssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  CampanhasRoute: CampanhasRoute,
  ClientesRoute: ClientesRoute,
  ConversasRoute: ConversasRoute,
  EntregasRoute: EntregasRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  IndicacoesRoute: IndicacoesRoute,
  PdvRoute: PdvRoute,
  PedidosRoute: PedidosRoute,
  ProdutosProcuradosRoute: ProdutosProcuradosRoute,
  RecompraPrevistaRoute: RecompraPrevistaRoute,
  ApiCrmAssistenteRoute: ApiCrmAssistenteRoute,
  ApiCrmClientesRoute: ApiCrmClientesRoute,
  ApiCrmConversasRoute: ApiCrmConversasRoute,
  ApiCrmDashboardRoute: ApiCrmDashboardRoute,
  ApiCrmIndicacoesRoute: ApiCrmIndicacoesRoute,
  ApiCrmPedidosRoute: ApiCrmPedidosRoute,
  ApiCrmPixRoute: ApiCrmPixRoute,
  ApiCrmProdutosRoute: ApiCrmProdutosRoute,
  ApiCrmProdutosProcuradosRoute: ApiCrmProdutosProcuradosRoute,
  ApiMercadopagoWebhookRoute: ApiMercadopagoWebhookRoute,
  ApiUazapiTestRoute: ApiUazapiTestRoute,
  ApiWebhookPagamentoRoute: ApiWebhookPagamentoRoute,
  ApiWebhookWhatsappRoute: ApiWebhookWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
